version: '3'
services:
    nginx:
        image: nginx:latest
        container_name: nginx_reverse_proxy
        volumes:
            -  ./tensorboard/plugins/projector/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 6006:6006